### ISSUE TITLE
SQL Error when trying to import ab file.

### ISSUE THREAD

**Issue by vyrzdev** [waicool20/mr2tachiyomi#12]
[MR2Tachiyomi] [2019-12-09 20:32:22] [Exposed] WARN - Transaction attempt #0 failed: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id). Statement(s): CREATE TABLE IF NOT EXISTS MangaChapter (_id INTEGER PRIMARY KEY, manga_id INT NOT NULL, num_pages INT NOT NULL, oid VARCHAR(1024) NOT NULL, chapter_order INT NOT NULL, title VARCHAR(1024) NOT NULL, _id INT NULL, CONSTRAINT fk_MangaChapter__id__id FOREIGN KEY (_id) REFERENCES MangaChapterLocal(_id) ON DELETE RESTRICT ON UPDATE RESTRICT)
org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:48)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:131)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:125)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:101)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:92)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter$convert$1.invoke(CsvConverter.kt:37)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter$convert$1.invoke(CsvConverter.kt:31)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:103)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter.convert(CsvConverter.kt:36)
	at com.waicool20.mr2tachiyomi.MR2Tachiyomi.convert(MR2Tachiyomi.kt:92)
	at com.waicool20.mr2tachiyomi.MR2TachiyomiKt.main(MR2Tachiyomi.kt:72)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:214)
	at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:25)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:46)
	... 19 common frames omitted
[MR2Tachiyomi] [2019-12-09 20:32:22] [Exposed] WARN - Transaction attempt #1 failed: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id). Statement(s): CREATE TABLE IF NOT EXISTS MangaChapter (_id INTEGER PRIMARY KEY, manga_id INT NOT NULL, num_pages INT NOT NULL, oid VARCHAR(1024) NOT NULL, chapter_order INT NOT NULL, title VARCHAR(1024) NOT NULL, _id INT NULL, CONSTRAINT fk_MangaChapter__id__id FOREIGN KEY (_id) REFERENCES MangaChapterLocal(_id) ON DELETE RESTRICT ON UPDATE RESTRICT)
org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:48)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:131)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:125)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:101)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:92)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter$convert$1.invoke(CsvConverter.kt:37)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter$convert$1.invoke(CsvConverter.kt:31)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:103)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter.convert(CsvConverter.kt:36)
	at com.waicool20.mr2tachiyomi.MR2Tachiyomi.convert(MR2Tachiyomi.kt:92)
	at com.waicool20.mr2tachiyomi.MR2TachiyomiKt.main(MR2Tachiyomi.kt:72)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:214)
	at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:25)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:46)
	... 19 common frames omitted
[MR2Tachiyomi] [2019-12-09 20:32:22] [Exposed] WARN - Transaction attempt #2 failed: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id). Statement(s): CREATE TABLE IF NOT EXISTS MangaChapter (_id INTEGER PRIMARY KEY, manga_id INT NOT NULL, num_pages INT NOT NULL, oid VARCHAR(1024) NOT NULL, chapter_order INT NOT NULL, title VARCHAR(1024) NOT NULL, _id INT NULL, CONSTRAINT fk_MangaChapter__id__id FOREIGN KEY (_id) REFERENCES MangaChapterLocal(_id) ON DELETE RESTRICT ON UPDATE RESTRICT)
org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:48)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:131)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:125)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:101)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:92)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter$convert$1.invoke(CsvConverter.kt:37)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter$convert$1.invoke(CsvConverter.kt:31)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:103)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter.convert(CsvConverter.kt:36)
	at com.waicool20.mr2tachiyomi.MR2Tachiyomi.convert(MR2Tachiyomi.kt:92)
	at com.waicool20.mr2tachiyomi.MR2TachiyomiKt.main(MR2Tachiyomi.kt:72)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:214)
	at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:25)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:46)
	... 19 common frames omitted
[MR2Tachiyomi] [2019-12-09 20:32:22] [c.w.m.MR2Tachiyomi] ERROR - Could not convert database file to csv due to unknown exception
org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:48)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:131)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:125)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:101)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:92)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter$convert$1.invoke(CsvConverter.kt:37)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter$convert$1.invoke(CsvConverter.kt:31)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:103)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter.convert(CsvConverter.kt:36)
	at com.waicool20.mr2tachiyomi.MR2Tachiyomi.convert(MR2Tachiyomi.kt:92)
	at com.waicool20.mr2tachiyomi.MR2TachiyomiKt.main(MR2Tachiyomi.kt:72)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:214)
	at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:25)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:46)
	... 19 common frames omitted
org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id)
SQL: [CREATE TABLE IF NOT EXISTS MangaChapter (_id INTEGER PRIMARY KEY, manga_id INT NOT NULL, num_pages INT NOT NULL, oid VARCHAR(1024) NOT NULL, chapter_order INT NOT NULL, title VARCHAR(1024) NOT NULL, _id INT NULL, CONSTRAINT fk_MangaChapter__id__id FOREIGN KEY (_id) REFERENCES MangaChapterLocal(_id) ON DELETE RESTRICT ON UPDATE RESTRICT)]
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:48)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:131)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:125)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:101)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:92)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:157)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter$convert$1.invoke(CsvConverter.kt:37)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter$convert$1.invoke(CsvConverter.kt:31)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:103)
	at com.waicool20.mr2tachiyomi.converters.CsvConverter.convert(CsvConverter.kt:36)
	at com.waicool20.mr2tachiyomi.MR2Tachiyomi.convert(MR2Tachiyomi.kt:92)
	at com.waicool20.mr2tachiyomi.MR2TachiyomiKt.main(MR2Tachiyomi.kt:72)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: _id)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:214)
	at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:25)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:46)
	... 19 more

**Comment by TahsinGokalp** [comment]
If you are using unrooted option uncheck 'App Data Only' option.

**Comment by jhat12345** [comment]
I get the same error. Here are my files and log. 
I uninstalled Java and installed jdk 8. I successfully connected Helium to my PC. Backed up (not 'app data only') MangaRock in Helium. Nothing happens when I try opening the `mr2tachiyomi.jar`
I used the command line of 
`java -jar mr2tachiyomi.jar -i com.notabasement.mangarock.android.titan.ab -o output.json` 
This is the error log. [Pastebin](https://pastebin.com/t40mSpeK)
Here are my files. [gDrive](https://drive.google.com/open?id=1ZP5bubekYRHVehkDiWijBMN_kf7r2QU6)

**Comment by waicool20** [comment]
Issue was that the package name was different, before it was `com.notabasement.mangarock.android.lotus`, however some users backup seem to have package name `com.notabasement.mangarock.android.titan` , tool now accounts for some variations in it.
